rosparam set /my_robo/diff_drive_controller/angular/z/has_acceleration_limits True
rosparam set /my_robo/diff_drive_controller/angular/z/has_velocity_limits True
rosparam set /my_robo/diff_drive_controller/angular/z/max_acceleration 1.5
rosparam set /my_robo/diff_drive_controller/angular/z/max_velocity 1.5
rosparam set /my_robo/diff_drive_controller/angular/z/min_acceleration -1.5
rosparam set /my_robo/diff_drive_controller/angular/z/min_velocity -1.5
rosparam set /my_robo/diff_drive_controller/cmd_vel_timeout 10.0
rosparam set /my_robo/diff_drive_controller/linear/x/has_acceleration_limits True
rosparam set /my_robo/diff_drive_controller/linear/x/has_velocity_limits True
rosparam set /my_robo/diff_drive_controller/linear/x/max_acceleration 1.0
rosparam set /my_robo/diff_drive_controller/linear/x/max_velocity 0.8
rosparam set /my_robo/diff_drive_controller/linear/x/min_acceleration -1.0
rosparam set /my_robo/diff_drive_controller/linear/x/min_velocity -0.8
rosparam set /my_robo/diff_drive_controller/wheel_radius 0.075
rosparam set /my_robo/diff_drive_controller/wheel_separation 0.285